### ISSUE TITLE
Crash when ship with docked cargo container jumps out.

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1177]
BP AoA mission "The Great Preservers"
Crash happens when Djinn jumps out.
Release and debug builds are affected. No warning or error in log.

backtrace
```
Thread 1 "fs2_open_3_7_5_" received signal SIGSEGV, Segmentation fault.
0x0000555555cc1372 in dock_evaluate_all_docked_objects (
    objp=0x5555568f0860 <Objects+106400>, infop=0x7fffffffdae0, 
    function=0x555555e02fde <ship_actually_depart_helper(object*, dock_function_info*)>) at /home/tomi/fs2open.github.com/code/object/objectdock.cpp:339
339			function(objp->dock_list->docked_objp, infop);
(gdb) bt
#0  0x0000555555cc1372 in dock_evaluate_all_docked_objects (
    objp=0x5555568f0860 <Objects+106400>, infop=0x7fffffffdae0, 
    function=0x555555e02fde <ship_actually_depart_helper(object*, dock_function_info*)>) at /home/tomi/fs2open.github.com/code/object/objectdock.cpp:339
#1  0x0000555555e030ba in ship_actually_depart (shipnum=30, method=4)
    at /home/tomi/fs2open.github.com/code/ship/ship.cpp:7341
#2  0x0000555555e49813 in WarpEffect::warpEnd (this=0x555566b18410)
    at /home/tomi/fs2open.github.com/code/ship/shipfx.cpp:3411
#3  0x0000555555e4a577 in WE_Default::warpFrame (this=0x555566b18410, 
    frametime=0.0293731689)
    at /home/tomi/fs2open.github.com/code/ship/shipfx.cpp:3654
#4  0x0000555555e41fdc in shipfx_warpout_frame (
    objp=0x5555568f0860 <Objects+106400>, frametime=0.0293731689)
    at /home/tomi/fs2open.github.com/code/ship/shipfx.cpp:864
#5  0x0000555555e078ce in ship_process_post (
    obj=0x5555568f0860 <Objects+106400>, frametime=0.0293731689)
    at /home/tomi/fs2open.github.com/code/ship/ship.cpp:8925
#6  0x0000555555cbdf4c in obj_move_all_post (
    objp=0x5555568f0860 <Objects+106400>, frametime=0.0293731689)
    at /home/tomi/fs2open.github.com/code/object/object.cpp:1227
#7  0x0000555555cbec61 in obj_move_all (frametime=0.0293731689)
    at /home/tomi/fs2open.github.com/code/object/object.cpp:1453
#8  0x000055555590788e in game_simulation_frame ()
---Type <return> to continue, or q <return> to quit---
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:3877
#9  0x0000555555908478 in game_frame (paused=false)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:4270
#10 0x0000555555909111 in game_do_frame ()
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:4677
#11 0x000055555590b593 in game_do_state (state=2)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6376
#12 0x00005555559e27ae in gameseq_process_events ()
    at /home/tomi/fs2open.github.com/code/gamesequence/gamesequence.cpp:409
#13 0x000055555590c2d6 in game_main (argc=1, argv=0x7fffffffe248)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6919
#14 0x000055555590e657 in actual_main (argc=1, argv=0x7fffffffe248)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:8108
#15 0x000055555590e7d4 in main (argc=1, argv=0x7fffffffe248)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:8153
```

git bisect
```
95315d7f8aa1ea8697c432f15b8d04b73a870cc9 is the first bad commit
commit 95315d7f8aa1ea8697c432f15b8d04b73a870cc9
Author: z64555 <z1281110@gmail.com>
Date:   Wed Jan 25 20:12:01 2017 -0600

    Optimizes dock_undock_objects() and dock_dead_undock_objects() methods by removing their dock pair check, because the same check is done in the remove_instance subroutines.
    * Adds a warning for debug users when an unknown ship_state is passed to red_alert_delete.
    * Removes commented-out code
    * Doxy's ship_cleanup()
    
    *Conform to each file's style.
    
    *Extend ship_cleanup to better handle red-alert deletion.
    *Also treat cleanup_mode as a flagset, instead of an enum as it was previously.

:040000 040000 fd6e18ef90c8b51beaeda3d87583abb937532390 04c0ad79c273b79c89b2a4951fbc4d9ac0dff794 M	code
```

**Comment by asarium** [comment]
@z64555 Looks like there is a bug in the code you added.

**Comment by z64555** [comment]
Is Djinn docked with anybody?

**Comment by tomimaki** [comment]
With container when it jumps out.

**Comment by z64555** [comment]
Ok, when does the crash occur, right as they're opening the portal? When they're halfway in? When they're all the way in the portal?

**Comment by tomimaki** [comment]
Third position. When they are all the way in the portal.

**Comment by z64555** [comment]
Cause found. Will make patch shortly.

**Comment by asarium** [comment]
@tomimaki Could you confirm that the bug has been fixed in the latest nightly?

**Comment by tomimaki** [comment]
Yes, fixed. Thanks.
