### ISSUE TITLE
#1866 causes FSO to crash

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1869]
Release build crash and debug build shows this:
```
ASSERTION: "Polygon_models[num]" at modelread.cpp:3184
 No model with id 0 found. Please backtrace and investigate.
```
```
Thread 1 "fs2_open_3_8_1_" received signal SIGTRAP, Trace/breakpoint trap.
debug_int3 (file=0x555556486c80 "/home/tomi/fs2open.github.com/code/osapi/dialogs.cpp", line=355) at /home/tomi/fs2open.github.com/code/osapi/osapi.cpp:485
485		gr_activate(1);
(gdb) bt
#0  0x000055555603003c in debug_int3(char const*, int) (file=0x555556486c80 "/home/tomi/fs2open.github.com/code/osapi/dialogs.cpp", line=355)
    at /home/tomi/fs2open.github.com/code/osapi/osapi.cpp:485
#1  0x00005555560362ef in os::dialogs::Error(char const*) (text=0x5555a397d500 "Assert: \"Polygon_models[num]\"\nFile: modelread.cpp\nLine: 3184\nNo model with id 0 found. Please backtrace and investigate.\n\n\n  /home/tomi/FreeSpace2/fs2_open_3_8_1_x64-DEBUG : os::dialogs::AssertMessage"...) at /home/tomi/fs2open.github.com/code/osapi/dialogs.cpp:355
#2  0x0000555556035494 in os::dialogs::AssertMessage(char const*, char const*, int, char const*, ...) (text=0x55555646f886 "Polygon_models[num]", filename=0x55555646da09 "modelread.cpp", linenum=3184, format=0x55555646f848 "No model with id %d found. Please backtrace and investigate.\n") at /home/tomi/fs2open.github.com/code/osapi/dialogs.cpp:148
#3  0x0000555555f5b62a in model_get(int) (model_num=600) at /home/tomi/fs2open.github.com/code/model/modelread.cpp:3184
#4  0x0000555555f7136a in model_render_queue(model_render_params*, model_draw_list*, int, matrix*, vec3d*) (interp=0x7fffffffd6c0, scene=0x7fffffffdab0, model_num=600, orient=0x555556c540dc <Objects+423228>, pos=0x555556c540d0 <Objects+423216>) at /home/tomi/fs2open.github.com/code/model/modelrender.cpp:2585
#5  0x0000555555cbb961 in warpin_queue_render(model_draw_list*, object*, matrix*, vec3d*, int, float, float, float, bool, int, int, int) (scene=0x7fffffffdab0, obj=0x555556c540a0 <Objects+423168>, orient=0x555556c540dc <Objects+423228>, pos=0x555556c540d0 <Objects+423216>, texture_bitmap_num=987, radius=27.0548325, life_percent=0.21981068, max_radius=35.2735825, warp_3d=false, warp_glow_bitmap=912, warp_ball_bitmap=913, warp_model_id=600) at /home/tomi/fs2open.github.com/code/fireball/warpineffect.cpp:118
#6  0x0000555555cbaf97 in fireball_render(object*, model_draw_list*) (obj=0x555556c540a0 <Objects+423168>, scene=0x7fffffffdab0)
    at /home/tomi/fs2open.github.com/code/fireball/fireballs.cpp:1070
#7  0x000055555601ffc4 in obj_queue_render(object*, model_draw_list*) (obj=0x555556c540a0 <Objects+423168>, scene=0x7fffffffdab0)
    at /home/tomi/fs2open.github.com/code/object/object.cpp:1665
#8  0x00005555560282e6 in obj_render_queue_all() () at /home/tomi/fs2open.github.com/code/object/objectsort.cpp:361
#9  0x0000555555beee31 in game_render_frame(camid) (cid=...) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:3474
#10 0x0000555555bf04b7 in game_frame(bool) (paused=false) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:4172
#11 0x0000555555bf106d in game_do_frame() () at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:4551
#12 0x0000555555bf3505 in game_do_state(int) (state=2) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6250
#13 0x0000555555cd6fc8 in gameseq_process_events() () at /home/tomi/fs2open.github.com/code/gamesequence/gamesequence.cpp:403
#14 0x0000555555bf4263 in game_main(int, char**) (argc=1, argv=0x7fffffffe098) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6792
#15 0x0000555555bf6444 in actual_main(int, char**) (argc=1, argv=0x7fffffffe098) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:7981
#16 0x0000555555bf6585 in main(int, char**) (argc=1, argv=0x7fffffffe098) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:8026
```
It only happens **after restart mission** sooner or later. For example: Colateral Damage from BP (sooner) or Sixth Wonder from Mediavps 3.8 (later). 
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/2407664/fs2_open.log)

**Comment by Goober5000** [comment]
As best I can determine, this is caused by the warp.pof model not being preserved between level loads.  My new PR should fix it.

**Comment by tomimaki** [comment]
Thanks, that fixed issue.
