### ISSUE TITLE
Crash after #2449 in 3. mission "Bailed Out" (LCW-3.fs2) Luyten Civil War campaign

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#2501]
Crash occurs when Taurus wing show up and do some damage.
```
Thread 1 "fs2_open_20_1_0" received signal SIGSEGV, Segmentation fault.
sexp_get_damage_caused (node=1909) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:8557
8557				attacker_sig = attacker->objp->signature;
(gdb) bt
#0  sexp_get_damage_caused(int) (node=1909) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:8557
#1  0x000055555649b5a5 in eval_sexp(int, int) (cur_node=1907, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23748
#2  0x000055555649aaa3 in eval_sexp(int, int) (cur_node=1910, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23294
#3  0x000055555646c030 in sexp_number_compare(int, int) (n=1910, op=1542) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:5304
#4  0x000055555649aece in eval_sexp(int, int) (cur_node=1906, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23423
#5  0x0000555556499ebc in is_sexp_true(int, int) (cur_node=1906, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23028
#6  0x000055555646af2b in sexp_or(int) (n=1912) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:5095
#7  0x000055555649ae81 in eval_sexp(int, int) (cur_node=1905, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23402
#8  0x000055555649aaa3 in eval_sexp(int, int) (cur_node=1920, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23294
#9  0x0000555556499ebc in is_sexp_true(int, int) (cur_node=1920, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23028
#10 0x000055555646b405 in sexp_and(int) (n=1904) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:5147
#11 0x000055555649ae93 in eval_sexp(int, int) (cur_node=1901, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23406
#12 0x0000555556476283 in test_argument_nodes_for_condition(int, int, int*, int*, int*, int*)
    (n=1898, condition_node=1901, num_true=0x7fffffffdb24, num_false=0x7fffffffdb20, num_known_true=0x7fffffffdb1c, num_known_false=0x7fffffffdb18)
    at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:9604
#13 0x00005555564768c8 in eval_any_of(int, int) (arg_handler_node=1895, condition_node=1901) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:9756
#14 0x000055555649b657 in eval_sexp(int, int) (cur_node=1895, referenced_node=1901) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23793
#15 0x0000555556475bad in eval_when(int, int) (n=1900, when_op_num=2817) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:9437
#16 0x000055555649b5f7 in eval_sexp(int, int) (cur_node=1894, referenced_node=-1) at /home/tomi/fs2open.github.com/code/parse/sexp.cpp:23771
#17 0x00005555562c1742 in mission_process_event(int) (event=66) at /home/tomi/fs2open.github.com/code/mission/missiongoals.cpp:946
#18 0x00005555562c1ff2 in mission_eval_goals() () at /home/tomi/fs2open.github.com/code/mission/missiongoals.cpp:1104
#19 0x0000555555f73a46 in game_simulation_frame() () at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:3534
#20 0x0000555555f74695 in game_frame(bool) (paused=false) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:3929
#21 0x0000555555f752f1 in game_do_frame() () at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:4293
#22 0x0000555555f77947 in game_do_state(int) (state=2) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:5958
#23 0x0000555556067733 in gameseq_process_events() () at /home/tomi/fs2open.github.com/code/gamesequence/gamesequence.cpp:386
#24 0x0000555555f786ab in game_main(int, char**) (argc=1, argv=0x7fffffffe078) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6434
#25 0x0000555555f7a91d in main(int, char**) (argc=1, argv=0x7fffffffe078) at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:7475
```
Git bisect shows me #2449 
```
bfc8075226da99f46d7973aa0e58b8925fba5385 is the first bad commit
commit bfc8075226da99f46d7973aa0e58b8925fba5385
Author: Goober5000 <ipw47@mailbox.org>
Date:   Sun Jun 7 00:33:32 2020 -0400

    upgrade the objective sexps 2
    
    There's another chunk of objective sexps farther down in sexp.cpp, so this PR addresses those.

 code/parse/sexp.cpp | 443 +++++++++++++++++++++++-----------------------------
 1 file changed, 198 insertions(+), 245 deletions(-)
```

**Comment by Goober5000** [comment]
Strange... if the attacker is present, the `objp` variable *should* be valid.

**Comment by tomimaki** [comment]
Tested fix and it works.
