### ISSUE TITLE
Crash when player is targeting SJD Sathanas at Knossos in "Into the Lion's Den"

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#3062]
Release build crashes to desktop. Doesn't matter if MVPS or retail.

Backtrace:
```
#0  debug_int3(char const*, int)
    (file=0x555556d0a628 "/home/tomi/fs2open.github.com/code/model/modelrender.cpp", line=874) at /home/tomi/fs2open.github.com/code/osapi/osapi.cpp:585
#1  0x000055555650c261 in model_render_add_lightning(model_draw_list*, model_render_params*, polymodel*, submodel_instance*)
    (scene=0x7fffffffd8f0, interp=0x7fffffffdb40, pm=0x555571ad7fd0, smi=0x55558d67ad60) at /home/tomi/fs2open.github.com/code/model/modelrender.cpp:874
#2  0x000055555650d9a0 in model_render_children_buffers(model_draw_list*, model_material*, model_render_params*, polymodel*, polymodel_instance*, int, int, unsigned int, bool)
    (scene=0x7fffffffd8f0, rendering_material=0x7fffffffd710, interp=0x7fffffffdb40, pm=0x555571ad7fd0, pmi=0x55558e535d90, mn=56, detail_level=0, tmap_flags=603, trans_buffer=false)
    at /home/tomi/fs2open.github.com/code/model/modelrender.cpp:1294
#3  0x0000555556512ed5 in model_render_queue(model_render_params*, model_draw_list*, int, int, matrix*, vec3d*)
    (interp=0x7fffffffdb40, scene=0x7fffffffd8f0, model_num=4814, model_instance_num=0, orient=0x55555763055c <Objects+23740>, pos=0x7fffffffdcc4)
    at /home/tomi/fs2open.github.com/code/model/modelrender.cpp:2764
#4  0x00005555565121aa in model_render_immediate(model_render_params*, int, int, matrix*, vec3d*, int, bool)
    (render_info=0x7fffffffdb40, model_num=4814, model_instance_num=-1, orient=0x55555763055c <Objects+23740>, pos=0x7fffffffdcc4, render=3, sort=true)
    at /home/tomi/fs2open.github.com/code/model/modelrender.cpp:2499
#5  0x000055555651210e in model_render_immediate(model_render_params*, int, matrix*, vec3d*, int, bool)
    (render_info=0x7fffffffdb40, model_num=4814, orient=0x55555763055c <Objects+23740>, pos=0x7fffffffdcc4, render=3, sort=true)
    at /home/tomi/fs2open.github.com/code/model/modelrender.cpp:2490
#6  0x00005555563b9ad8 in HudGaugeTargetBox::renderTargetShip(object*)
    (this=0x555559bd7d80, target_objp=0x555557630520 <Objects+23680>)
    at /home/tomi/fs2open.github.com/code/hud/hudtargetbox.cpp:639
#7  0x00005555563b8ef9 in HudGaugeTargetBox::render(float)
    (this=0x555559bd7d80, frametime=0.0309906006)
    at /home/tomi/fs2open.github.com/code/hud/hudtargetbox.cpp:391
#8  0x00005555563132f2 in hud_render_gauges(int) (cockpit_display_num=-1)
    at /home/tomi/fs2open.github.com/code/hud/hud.cpp:1833
#9  0x0000555556312e96 in hud_render_all() ()
    at /home/tomi/fs2open.github.com/code/hud/hud.cpp:1748
#10 0x00005555560c825d in game_render_hud(camid) (cid=...)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:3712
#11 0x00005555560c8c92 in game_frame(bool) (paused=false)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:3986
#12 0x00005555560c976f in game_do_frame(bool) (set_frametime=true)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:4307
#13 0x00005555560cc599 in game_do_state(int) (state=2)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6041
#14 0x00005555561cae0f in gameseq_process_events() ()
    at /home/tomi/fs2open.github.com/code/gamesequence/gamesequence.cpp:386
#15 0x00005555560cd32b in game_main(int, char**) (argc=1, argv=0x7fffffffe108)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6518
#16 0x00005555560cf5c6 in main(int, char**) (argc=1, argv=0x7fffffffe108)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:7570
```

Git bisect:
```
c18b1b63fd735d28b60e391d7da8a5e6069df835 is the first bad commit
commit c18b1b63fd735d28b60e391d7da8a5e6069df835
Author: Goober5000 <ipw47@mailbox.org>
Date:   Sat Dec 19 00:51:51 2020 -0500

    another model to model_instance refactor
    
    Remove arc information from bsp_info and move it to submodel_instance.  Add a model instance to each debris chunk to keep track of it.

 code/debris/debris.cpp     | 21 ++++++-----
 code/debris/debris.h       |  2 ++
 code/graphics/shadows.cpp  |  5 ++-
 code/hud/hudtargetbox.cpp  |  5 ++-
 code/model/model.h         | 67 ++++++++++++++++++++----------------
 code/model/modelread.cpp   | 78 ++++++++++++++---------------------------
 code/model/modelrender.cpp | 86 +++++++++++++++++++++-------------------------
 code/model/modelrender.h   |  4 +--
 code/object/object.cpp     | 38 ++++++++++++++++++++
 code/object/object.h       |  1 +
 code/ship/ship.cpp         |  6 +++-
 code/ship/shipfx.cpp       |  5 +--
 12 files changed, 175 insertions(+), 143 deletions(-)
```

**Comment by asarium** [comment]
@Goober5000 Could you take a look?
