### ISSUE TITLE
error: cannot construct `mat3' from a matrix in GLSL 1.10 (GLSL 1.20 or GLSL ES 1.00 required)

### ISSUE THREAD

**Issue by rtoijala** [scp-fs2open/fs2open.github.com#886]
When starting the game, the log fills with lots of errors as below.
Models in the tech room are displayed completely white.
The game crashes when starting a mission (backtrace below).

x86_64 Arch Linux, mesa 12.0.1 intel, FSO git 05abf8b0418a25de9f5895a59feb43d1cb0a2480

Error:
```
Compiling new shader:
        Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
Vertex shader failed to compile:
0:120(44): error: cannot construct `mat3' from a matrix in GLSL 1.10 (GLSL 1.20 or GLSL ES 1.00 required)
0:120(26): error: operands to arithmetic operators must be numeric
0:120(26): error: operands to arithmetic operators must be numeric
0:120(16): error: no matching function for call to `normalize(error)'; candidates are:
0:120(16): error:    float normalize(float)
0:120(16): error:    vec2 normalize(vec2)
0:120(16): error:    vec3 normalize(vec3)
0:120(16): error:    vec4 normalize(vec4)
0:121(12): warning: `normal' used uninitialized

ERROR! Unable to create vertex shader!
```

Backtrace:
```
#0  debug_int3 (file=0xd3c810 "/home/risto/fs2/fs2open.github.com/code/graphics/gropenglshader.cpp", line=782)
    at /home/risto/fs2/fs2open.github.com/code/osapi/osapi.cpp:378
#1  0x0000000000833159 in opengl_shader_get_attribute (
    attribute_text=0x133e938 <GL_array_binding_data+536> "model_id")
    at /home/risto/fs2/fs2open.github.com/code/graphics/gropenglshader.cpp:782
#2  0x000000000081c386 in opengl_bind_vertex_component (vert_component=...)
    at /home/risto/fs2/fs2open.github.com/code/graphics/gropengldraw.cpp:233
#3  0x000000000081c43f in opengl_bind_vertex_layout (layout=...)
    at /home/risto/fs2/fs2open.github.com/code/graphics/gropengldraw.cpp:252
#4  0x000000000084a0cf in opengl_init_arrays (vbp=0x43c2278, bufferp=0x61efc58)
    at /home/risto/fs2/fs2open.github.com/code/graphics/gropengltnl.cpp:760
#5  0x000000000084a94b in opengl_render_pipeline_fixed (start=0, bufferp=0x61efc58, datap=0x62d3d38, flags=283)
    at /home/risto/fs2/fs2open.github.com/code/graphics/gropengltnl.cpp:988
#6  0x000000000084a395 in opengl_render_pipeline_program (start=0, bufferp=0x61efc58, datap=0x62d3d38, 
    flags=283) at /home/risto/fs2/fs2open.github.com/code/graphics/gropengltnl.cpp:823
#7  0x000000000084b8d1 in gr_opengl_render_buffer (start=0, bufferp=0x61efc58, texi=0, flags=283)
    at /home/risto/fs2/fs2open.github.com/code/graphics/gropengltnl.cpp:1325
#8  0x0000000000a0ce85 in gr_render_buffer (start=0, bufferp=0x61efc58, texi=0, flags=283)
    at /home/risto/fs2/fs2open.github.com/code/graphics/2d.h:874
#9  0x0000000000a050d7 in draw_list::render_buffer (this=0x7ffd91d822d0, render_elements=...)
    at /home/risto/fs2/fs2open.github.com/code/model/modelrender.cpp:647
#10 0x0000000000a059c7 in draw_list::render_all (this=0x7ffd91d822d0, depth_mode=2)
    at /home/risto/fs2/fs2open.github.com/code/model/modelrender.cpp:874
#11 0x0000000000abd854 in obj_render_queue_all ()
    at /home/risto/fs2/fs2open.github.com/code/object/objectsort.cpp:405
#12 0x00000000007209ea in game_render_frame (cid=...)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:3737
#13 0x0000000000721f53 in game_frame (paused=false)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:4419
#14 0x0000000000722ad6 in game_do_frame () at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:4797
#15 0x0000000000724df4 in game_do_state (state=2)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:6494
#16 0x00000000007edb67 in gameseq_process_events ()
    at /home/risto/fs2/fs2open.github.com/code/gamesequence/gamesequence.cpp:409
#17 0x0000000000725afe in game_main (argc=2, argv=0x7ffd91d82888)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:7032
#18 0x0000000000727ffc in actual_main (argc=2, argv=0x7ffd91d82888)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:8608
#19 0x000000000072811d in main (argc=2, argv=0x7ffd91d82888)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:8649
```

**Comment by asarium** [comment]
We are aware of this issue. #844 is very close to being merged which will probably fix these issues (at least they fixed the issues for me...).

**Comment by Echelon9** [comment]
@rtoijala Thanks for the report. This is a duplicate of the know https://github.com/scp-fs2open/fs2open.github.com/issues/235.
