### ISSUE TITLE
Null vec3d in vec3d normalize.\nTrace out of vecmat.cpp and find offending code.\n

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#988]
Mod fsport.
Issue occurs on ship or weapon selection screen, when shadows and ship_choice_3d or weapon_choice_3d are enabled.

```
Thread 1 "fs2_open_3_7_5_" received signal SIGTRAP, Trace/breakpoint trap.
debug_int3 (
    file=0xda4730 "/home/tomi/fs2open.github.com/code/osapi/dialogs.cpp", 
    line=431) at /home/tomi/fs2open.github.com/code/osapi/osapi.cpp:378
378     gr_activate(1);
(gdb) bt
#0  debug_int3 (
    file=0xda4730 "/home/tomi/fs2open.github.com/code/osapi/dialogs.cpp", 
    line=431) at /home/tomi/fs2open.github.com/code/osapi/osapi.cpp:378
#1  0x0000000000ae6f57 in os::dialogs::ReleaseWarning (
    filename=0xd75908 "vecmat.cpp", line=437, format=0xda47c5 "%s")
    at /home/tomi/fs2open.github.com/code/osapi/dialogs.cpp:431
#2  0x0000000000ae7146 in os::dialogs::Warning (
    filename=0xd758e0 "/home/tomi/fs2open.github.com/code/math/vecmat.cpp", 
    line=437, 
    format=0xd759e8 "Null vec3d in vec3d normalize.\nTrace out of vecmat.cpp and find offending code.\n")
    at /home/tomi/fs2open.github.com/code/osapi/dialogs.cpp:451
#3  0x00000000009496f7 in vm_vec_copy_normalize (dest=0x7fffffffdb60, 
    src=0x7fffffffdb60)
    at /home/tomi/fs2open.github.com/code/math/vecmat.cpp:438
#4  0x00000000009497a4 in vm_vec_normalize (v=0x7fffffffdb60)
    at /home/tomi/fs2open.github.com/code/math/vecmat.cpp:462
#5  0x000000000094a711 in vm_vector_2_matrix (m=0x7fffffffdb60, 
    fvec=0x7fffffffdb90, uvec=0x1951e2c <Eye_matrix+12>, rvec=0x0)
    at /home/tomi/fs2open.github.com/code/math/vecmat.cpp:881
#6  0x000000000083172f in shadows_start_render (
    eye_orient=0x1951e20 <Eye_matrix>, eye_pos=0x1951e48 <Eye_position>, 
    fov=0.907571256, aspect=1.77864587, veryneardist=45.5714417, 
---Type <return> to continue, or q <return> to quit---
    neardist=245.571442, middist=2045.57141, fardist=10045.5713)
    at /home/tomi/fs2open.github.com/code/graphics/shadows.cpp:373
#7  0x00000000009d4722 in draw_model_rotating (render_info=0x7fffffffdf10, 
    model_id=600, x1=412, y1=135, x2=629, y2=355, 
    rotation_buffer=0x158218c <ShipSelectScreenShipRot>, 
    closeup_pos=0x380e460, closeup_zoom=0.649999976, rev_rate=5.19999981, 
    flags=33619968, resize_mode=3, effect=1)
    at /home/tomi/fs2open.github.com/code/missionui/missionscreencommon.cpp:1900
#8  0x00000000009d85fc in ship_select_do (frametime=0.0421600342)
    at /home/tomi/fs2open.github.com/code/missionui/missionshipchoice.cpp:1480
#9  0x0000000000749d37 in game_do_state (state=11)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6416
#10 0x0000000000811417 in gameseq_process_events ()
    at /home/tomi/fs2open.github.com/code/gamesequence/gamesequence.cpp:409
#11 0x000000000074a989 in game_main (argc=1, argv=0x7fffffffe2a8)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:6906
#12 0x000000000074cde3 in actual_main (argc=1, argv=0x7fffffffe2a8)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:8481
#13 0x000000000074cf04 in main (argc=1, argv=0x7fffffffe2a8)
    at /home/tomi/fs2open.github.com/freespace2/freespace.cpp:8522
```

**Comment by DahBlount** [comment]
I've encountered this a few times as well.

**Comment by tomimaki** [comment]
Tested #1158. It fixes bug.

**Comment by z64555** [comment]
@tomimaki Thanks for testing!
